### ISSUE TITLE
Can't find the paper "Mapping Natural-language Problems to Formal-language Solutions Using Structured Neural Representations"

### ISSUE THREAD

**Issue by jackyuanjie1990** [ckzbullbullet/TP-N2F#1]
Hello,

Thank you for publishing your code. However, I can't find the paper "Mapping Natural-language Problems to Formal-language Solutions Using Structured Neural Representations". Is this same as the paper "NATURAL- TO FORMAL-LANGUAGE GENERATION
USING TENSOR PRODUCT REPRESENTATIONS"? https://arxiv.org/pdf/1910.02339.pdf

Best,

Jack

**Comment by ckzbullbullet** [comment]
Yes. Our paper was modified and accepted by ICML 2020. We will update the Arxiv version in the upcoming week.
